export function Section() {
    return(
        <>
        <section>
      <div>
        <h1>Section1</h1>
      </div>
      <div>
        <h2>Section2</h2>
      </div>
     </section>
      <section>
      <div>
        <h1>Section1</h1>
      </div>
      <div>
        <h2>Section2</h2>
      </div>
     </section>
      <section>
      <div>
        <h1>Section1</h1>
      </div>
      <div>
        <h2>Section2</h2>
      </div>
     </section>
     </>
    );
}